export const leaderboard = [
  ["OxKingLeooX", "0", "0", "https://www.twitch.tv/oxkingleoox"],
  ["McPlumber1",  "0", "0", "https://www.twitch.tv/mcplumber1"],
  ["KennyLaddd",  "0", "0", "https://www.twitch.tv/kennyladdd"],
  ["BennyTots",  "0", "0", "https://www.twitch.tv/bennytots"],
  ["CaptDanieldore",  "3", "5", "https://www.twitch.tv/captdanieldore"],
  ["Batcam22",  "0", "0", "https://www.twitch.tv/batcam22"],
  ["RoflmaoGamers1",  "0", "0", "https://www.twitch.tv/roflmaogamers1"],
  ["DorktownPhantom",  "0", "0", "https://www.twitch.tv/dorktown_phantom"],
  ["TheBrokenPirates",  "0", "0", "https://www.twitch.tv/thebrokenpirates"],
  ["HUZQI",  "0", "0", "https://twitch.tv/HUZQI"],
  ["Reilnur",  "0", "0", "https://www.twitch.tv/reilnur"],
  ["BemidgeGaming",  "0", "0", "https://www.twitch.tv/bemidgegaming"],
  ["BigMurph619",  "0", "0", "https://www.twitch.tv/bigmurph619"],
  ["CamMan52",  "0", "0", "https://www.twitch.tv/camman52"],
  ["Freestob",  "0", "0", "https://www.twitch.tv/freestob"],
  ["ElectricSoldierPorygon2",  "0", "0", "https://www.twitch.tv/ElectricSoldierPorygon2"],
  ["Ceedsy",  "0", "0", "https://www.twitch.tv/ceedsy"],
  ["Banana_Sen",  "0", "0", "https://www.twitch.tv/banana_sen"],
  ["imtripleshuriken",  "0", "0", "https://www.twitch.tv/imtripleshuriken"], 
];
